name: katalis2
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  provider: ^6.0.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  flutter_svg: ^2.0.14
  cloud_firestore: ^5.5.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  assets:
    - lib/assets/
    - lib/assets/image/
    - lib/assets/image/items/
    - lib/assets/image/logo.png
  uses-material-design: true
  fonts:
    - family: InstrumentSans
      fonts:
        - asset: lib/assets/fonts/InstrumentSans-Regular.ttf
        - asset: lib/assets/fonts/InstrumentSans-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/image/logo.png"
