// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg_9lM4ToXGmFVVNKGdI_Vjwi5nIIGK5w',
    appId: '1:1056255077153:web:109bff07156a177e042c60',
    messagingSenderId: '1056255077153',
    projectId: 'katalis2-44548',
    authDomain: 'katalis2-44548.firebaseapp.com',
    storageBucket: 'katalis2-44548.firebasestorage.app',
    measurementId: 'G-Z85T1L3S6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7-O5C6UpVluO4gQ0X9WvhpvRqGjvY_5c',
    appId: '1:1056255077153:android:d30f9c1deae60703042c60',
    messagingSenderId: '1056255077153',
    projectId: 'katalis2-44548',
    storageBucket: 'katalis2-44548.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQHOIs4fW1Bp-2cy3Y1hQaPNF8xpQFHEA',
    appId: '1:1056255077153:ios:0377eba8f6b7f9cf042c60',
    messagingSenderId: '1056255077153',
    projectId: 'katalis2-44548',
    storageBucket: 'katalis2-44548.firebasestorage.app',
    iosBundleId: 'com.example.katalis2',
  );
}
